myapp/models.py
import psycopg2
from flask_sqlalchemy import SQLAlchemy

from flask import current_app, g
from myapp import db, login_manager
from flask_login import UserMixin


@login_manager.user_loader
def load_user(user_id):
    return User.query.get(int(user_id))


class User(db.Model, UserMixin):
    __tablename__ = "user"
    id = db.Column(db.Integer, primary_key=True, autoincrement=True)
    username = db.Column(db.String(), unique=True, nullable=False)
    password = db.Column(db.String(), nullable=False)
    children = db.relationship("Page")

    def __repr__(self):
        return "User('{}')".format(self.username)


class Page(db.Model):
    __tablename__ = "pages"
    id = db.Column(db.Integer, primary_key=True, autoincrement=True)
    user_id = db.Column(db.Integer, db.ForeignKey("user.id"), nullable=False)
    order_number = db.Column(db.Integer)
    page_title = db.Column(db.Text(), nullable=False)
    page_url = db.Column(db.Text(), nullable=False)
    page_domain = db.Column(db.Text(), nullable=False)

    def __repr__(self):
        return "Page('{}', '{}')".format(self.page_title, self.page_url)


def init():
    db.create_all()

myapp/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, PasswordField, SubmitField, BooleanField
from wtforms.validators import DataRequired, Length, Email, EqualTo, ValidationError
from myapp.models import User


class RegistrationForm(FlaskForm):
    username = StringField("ユーザー名", validators=[DataRequired(), Length(min=2, max=20)])
    # email = StringField("Email", validators=[DataRequired(), Email()])
    password = PasswordField("パスワード", validators=[DataRequired()])
    confirm_password = PasswordField(
        "パスワードの確認", validators=[DataRequired(), EqualTo("password")]
    )
    submit = SubmitField("Sign Up")

    def validate_username(self, username):
        user = User.query.filter_by(username=username.data).first()
        if user:
            raise ValidationError("そのユーザー名はすでに使用されています 別の名前を入力してください")

    # def validate_email(self, email):
    #     email = User.query.filter_by(email=email.data).first()
    #     if email:
    #         raise ValidationError("That email is taken. Please choose a different one.")


class LoginForm(FlaskForm):
    # email = StringField("Email", validators=[DataRequired(), Email()])
    username = StringField("ユーザー名", validators=[DataRequired(), Length(min=2, max=20)])
    password = PasswordField("パスワード", validators=[DataRequired()])
    # remember = BooleanField("Remember me")
    submit = SubmitField("Login")


class PageForm(FlaskForm):
    page_title = StringField("page_title", validators=[DataRequired()])
    page_url = StringField("page_url", validators=[DataRequired()])
    page_domain = StringField("page_domain", validators=[DataRequired()])
    submit = SubmitField("Page")

myapp/__init__.py
"""
The flask application package.
"""
import os
from flask import Flask

from flask_sqlalchemy import SQLAlchemy

from flask_bcrypt import Bcrypt
from flask_login import LoginManager


app = Flask(__name__)
app.config.from_object("myapp.config")


db = SQLAlchemy(app)
db.init_app(app)

bcrypt = Bcrypt(app)
bcrypt.init_app(app)

login_manager = LoginManager(app)
login_manager.init_app(app)
login_manager.login_view = "bp_auth.login"
login_manager.login_message_category = "info"


import myapp.views

from myapp.auth import bp_auth

app.register_blueprint(bp_auth, url_prefix="/bp_auth")

from myapp.pages import bp_pages

app.register_blueprint(bp_pages, url_prefix="/bp_pages")

myapp/auth.py
from datetime import datetime

# import functools
from flask import (
    Blueprint,
    flash,
    g,
    redirect,
    render_template,
    request,
    session,
    url_for,
)

# from werkzeug.security import check_password_hash, generate_password_hash
from myapp import db, login_manager, bcrypt
from myapp.forms import RegistrationForm, LoginForm
from myapp.models import User, Page
from flask_login import login_user, current_user, logout_user, login_required

bp_auth = Blueprint(
    "bp_auth", __name__, template_folder="templates", static_folder="static"
)


@bp_auth.route("/create_user", methods=["GET", "POST"])
def create_user():
    form = RegistrationForm()
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode(
            "utf-8"
        )
        user = User(username=form.username.data, password=hashed_password)
        db.session.add(user)
        db.session.commit()
        flash(
            "{} さん として登録しました 続けて登録したユーザー名・パスワードを入力しログインしてください".format(
                form.username.data
            ),
            "success",
        )
        return redirect(url_for("bp_auth.login"))
    return render_template("bp_auth/create_user.html", title="新規登録", form=form)


@bp_auth.route("/login", methods=["GET", "POST"])
def login():
    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(username=form.username.data).first()
        if user and bcrypt.check_password_hash(user.password, form.password.data):
            login_user(user)
            # next_page = request.args.get("next")
            return redirect(url_for("input"))
        elif user is None:
            flash("ユーザー名が間違っています", "danger")
        else:
            flash("パスワードが間違っています", "danger")
    return render_template("bp_auth/login.html", title="ログイン", form=form)


@bp_auth.route("/logout")
def logout():
    logout_user()
    flash("ログアウトしました", "info")
    return redirect(url_for("input"))


# @bp_auth.before_app_request
# def load_logged_in_user():
#     """
#     どのURLが要求されても、ビュー関数の前で実行される関数
#     ログインしているか確認し、ログインされていればユーザー情報を取得する
#     """
#     user_id = session.get("user_id")

#     if user_id is None:
#         g.user = None
#     else:
#         db = get_db()
#         g.user = db.execute("SELECT * FROM user WHERE id = ?", (user_id,)).fetchone()


# def login_required(view):
#     """
#     ユーザーがログインされているかどうかをチェックし、
#     そうでなければログインページにリダイレクト
#     """

#     @functools.wraps(view)
#     def wrapped_view(**kwargs):
#         if g.user is None:
#             flash("ログインをしてから操作してください", category="alert alert-warning")
#             return redirect(url_for("bp_auth.login"))

#         return view(**kwargs)

#     return wrapped_view

myapp/views.py
from flask import (
    Flask,
    render_template,
    request,
    logging,
    Response,
    redirect,
    flash,
    url_for,
    session,
)
from datetime import datetime
from myapp import app
from myapp.models import User, Page
from flask_login import current_user, login_required


def UserInfo():
    try:
        pages = Page.query.filter_by(user_id=current_user.id).all()
        return pages
    except:
        pass


# userinfo = UserInfo() これを挟むとpagesが表示されない なぜだろう


@app.route("/")
def input():
    if not UserInfo():
        return render_template("input.html")
    else:
        return render_template("input.html", pages=UserInfo())


@app.route("/output", methods=["POST"])
def output():
    keyword = request.form["keyword"]
    keyword_on_site = str(request.form["keyword"] + " site:")
    if not UserInfo():
        return render_template(
            "output.html", keyword=keyword, keyword_on_site=keyword_on_site
        )
    else:
        return render_template(
            "output.html",
            keyword=keyword,
            keyword_on_site=keyword_on_site,
            pages=UserInfo(),
        )

myapp/templates/bp_auth/create_user.html
{% extends "layout.html" %}

{% block content %}

<div class="content-section">
    <form method="POST" action="">
        {{ form.hidden_tag() }}
        <fieldset class="form-group">
            <legend class="border-bottom md-4">さあ、始めよう</legend>
            <div class="form-group">
                {{ form.username.label(class="form-control-label") }}
                {% if form.username.errors %}
                {{ form.username(class="form-control form-control-lg is-invalid") }}
                <div class="invalid-feedback">
                    {% for error in form.username.errors %}
                    <span>{{ error }}</span>
                    {% endfor %}
                </div>
                {% else %}
                {{ form.username(class="form-control form-control-lg") }}
                {% endif %}
            </div>

            <div class="form-group">
                {{ form.password.label(class="form-control-label") }}
                {% if form.password.errors %}
                {{ form.password(class="form-control form-control-lg is-invalid") }}
                <div class="invalid-feedback">
                    {% for error in form.password.errors %}
                    <span>{{ error }}</span>
                    {% endfor %}
                </div>
                {% else %}
                {{ form.password(class="form-control form-control-lg") }}
                {% endif %}
            </div>

            <div class="form-group">
                {{ form.confirm_password.label(class="form-control-label") }}
                {% if form.confirm_password.errors %}
                {{ form.confirm_password(class="form-control form-control-lg is-invalid") }}
                <div class="invalid-feedback">
                    {% for error in form.confirm_password.errors %}
                    <span>{{ error }}</span>
                    {% endfor %}
                </div>
                {% else %}
                {{ form.confirm_password(class="form-control form-control-lg") }}
                {% endif %}
            </div>
            <button type="submit" class="btn btn-primary">登録</button>
        </fieldset>
    </form>
</div>

<!-- <form method="post">
    <div class="form-group">
        <label>ユーザー名</label>
        <input type="text" class="form-control" name="username">
    </div>
    <div class="form-group">
        <label>パスワード</label>
        <input type="password" class="form-control" name="password">
    </div>
    <button type="submit" class="btn btn-primary">登録</button>
</form> -->

{% endblock %}

myapp/templates/bp_auth/login.html
{% extends "layout.html" %}

{% block content %}

<div class="content-section">
    <form method="POST" action="">
        {{ form.hidden_tag() }}
        <fieldset class="form-group">
            <div class="form-group">
                {{ form.username.label(class="form-control-label") }}
                {% if form.username.errors %}
                {{ form.username(class="form-control form-control-lg is-invalid") }}
                <div class="invalid-feedback">
                    {% for error in form.username.errors %}
                    <span>{{ error }}</span>
                    {% endfor %}
                </div>
                {% else %}
                {{ form.username(class="form-control form-control-lg") }}
                {% endif %}
            </div>
            <div class="form-group">
                {{ form.password.label(class="form-control-label") }}
                {% if form.password.errors %}
                {{ form.password(class="form-control form-control-lg is-invalid") }}
                <div class="invalid-feedback">
                    {% for error in form.password.errors %}
                    <span>{{ error }}</span>
                    {% endfor %}
                </div>
                {% else %}
                {{ form.password(class="form-control form-control-lg") }}
                {% endif %}
            </div>
            <button type="submit" class="btn btn-primary">Sign-in</button>
        </fieldset>
    </form>
</div>

<!-- <form method="post">
    <div class="form-group">
        <label>ユーザー名</label>
        <input type="text" class="form-control" name="username">
    </div>
    <div class="form-group">
        <label>パスワード</label>
        <input type="password" class="form-control" name="password">
    </div>
    <button type="submit" class="btn btn-primary">Sign-in</button>
</form> -->

{% endblock %}

myapp/templates/bp_pages/create_page.html
{% extends "layout.html" %}

{% block content %}

<p class="memo">検索結果に追加したいWebサイトのタイトルを入れて検索して下さい<br>トップヒットしたサイトを表示します</p>

<div class="row">
    <hr class="hl">
</div>

{% if not result_display_link %}
<form method="post">
    <div class="form-group">
        <label class="label">Webサイトのタイトルを入力</label>
        <input type="text" class="form-control" name="search_keyword">
    </div>
    <button type="submit" class="btn btn-outline-primary">Search in Google</button>
</form>
{% else %}
<div class="result">
    <img src="http://www.google.com/s2/favicons?domain={{ result_display_link }}" class="card-favicon-img">
    <p class="p-result">{{ result_title }}</p>
</div>

<form class="register-btn" method="post" name="register" action="{{ url_for("bp_pages.register_page") }}">
    <button type="submit" class="btn btn-success">追加する</button>
</form>

<div class="error-note">
    <p class="sol-warn">追加後にエラーが出た場合はブラウザバックし、もう一度追加の操作をしてください</p>
    <p>正しく追加されていることが確認いただけます</p>
    <p class="solution">現在この問題の解決に向け取り組んでいます</p>
</div>

<div class="row">
    <hr class="hl">
</div>

<form method="post">
    <div class="form-group again">
        <label class="label">もう一度検索</label>
        <input type="text" class="form-control" name="search_keyword">
    </div>
    <button type="submit" class="btn btn-outline-primary">Search in Google</button>
</form>
{% endif %}



{% endblock %}

myapp/templates/bp_pages/index_page.html
{% extends "layout.html" %}
{% block content %}

<p class="memo">ここに追加したWebサイトが検索結果に追加され、結果を比較できます<br>自分好みに編集してみよう</p>

<table class="table table-hover">
    <!-- <thead>
            <tr>
                <th></th>
            </tr>
        </thead> -->
    <tbody class="tags">
        {% for pg in pages %}
        <tr>
            <td class="tag1"><img src="http://www.google.com/s2/favicons?domain={{ pg.page_domain }}"
                    class="card-favicon-img">
            </td>
            <td class="tag2">{{ pg.page_title }}</td>
            <td class="tag3">
                <!-- <a href="{{ url_for('bp_pages.update_page', page_id=pg.id) }}">編集</a>｜ -->
                <a class="a-tags del-tag" href="{{ url_for('bp_pages.delete_page', page_id=pg.id) }}">削除</a>
            </td>
        </tr>
        {% else %}
        <td>Pageはまだ登録されていません</td>
        {% endfor %}
    </tbody>
</table>

<div class="update-tag">
    <a class="a-tags" href="{{ url_for('bp_pages.create_page') }}">Pageの新規追加</a>
</div>
{% endblock %}

myapp/templates/input.html
<!DOCTYPE html>
<html lang="ja">

<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <title>Around Search</title>
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
    integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.11.2/css/all.css">
  <link rel="icon" href="../static/img/left_32.ico">
  <link rel="apple-touch-icon" sizes="151x151" href="../static/img/left_151.png">
  <link rel="stylesheet" href="../static/styles_input.css">
</head>

<body>
  <div class="container">

    <header>
      {% if current_user.is_authenticated %}
      <div class="navibar">
        <a class="item1" href="{{ url_for('bp_pages.index_pages') }}">Pages &raquo;</a>
        <a class="item2" href="{{ url_for('bp_auth.logout') }}">ログアウト</a>
        <p class="item3">{{ current_user.username }}</p>
      </div>
      {% else %}
      <div class="navibar">
        <a href="{{ url_for('bp_auth.create_user') }}">新規登録</a>
        <a href="{{ url_for('bp_auth.login') }}">ログイン</a>
      </div>
      {% endif %}
      <div class="row">
        <div class="col-md-12 title">
          <a href="/">
            <i class="fas fa-align-left d-inline-block"></i>
            <h1>Around Search</h1>
          </a>
        </div>
      </div>
    </header>

    <div class="row">
      <div class="col-md-12 div-form">
        <!-- <form class="form-inline my-2 my-lg-0" method="post" action="{{ url_for("output") }}>
          <input name="keyword" class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
          <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
        </form> -->

        <form class="form-inline form-input-go" method="post" action="{{ url_for("output") }}">
          <label class="sr-only" for="#">Search</label>
          <input name="keyword" type="search" class="form-control mr-sm-2 go-frame" placeholder="Go !" id="#">
          <button type="submit" class="btn btn-outline-success">Search</button>
        </form>
      </div>

    </div>

    <div class="row">
      <hr class="hl">
    </div>

    <div class="row headline">
      {% with messages = get_flashed_messages(with_categories=true) %}
      {% if messages %}
      {% for category, message in messages %}
      <div class="alert alert-{{ category }}">
        {{ message }}
      </div>
      {% endfor %}
      {% endif %}
      {% endwith %}
      <div class="below_message"></div>
    </div>


    {% if current_user.is_authenticated %}
    <div class="row headline">
      <h2>設定したPagesの一覧です</h2>
      {% if pages %}
      {% for pg in pages %}
      <p class="a_setted_own"><a href="{{ pg.page_url }}" target="_blank">{{ pg.page_title }}</a></p>
      {% endfor %}
      {% else %}
      <p>Pageはまだありません</p>
      <p>下のリンクから追加してみよう</p>
      {% endif %}
      <div class="guide_div guide-pages">
        <a class="guiding" href="{{ url_for('bp_pages.index_pages') }}">Pageの追加・削除</a>
      </div>
    </div>

    <div class="row">
      <hr class="hl">
    </div>

    <div class="row headline">
      <p><a href="https://ja.wikipedia.org/wiki" target="_blank">Wikipedia</a> | <a href="https://kotobank.jp"
          target="_blank">コトバンク</a> | <a href="https://dictionary.goo.ne.jp" target="_blank">goo 辞書</a> | <a
          href="https://matome.naver.jp" target="_blank">Naverまとめ</a></p>
      <p><a href="https://chiebukuro.yahoo.co.jp" target="_blank">Yahoo! 知恵袋</a> | <a href="https://oshiete.goo.ne.jp"
          target="_blank">教えて! goo</a> | <a href="https://qiita.com" target="_blank">Qiita</a></p>
      <p><a href="https://teratail.com" target="_blank">teratail</a> | <a href="https://ja.stackoverflow.com"
          target="_blank">Stack Overflow</a> | <a href="https://news.google.com/?hl=ja&gl=JP&ceid=JP:ja"
          target="_blank">Google ニュース</a></p>
      <p><a href="https://twitter.com" target="_blank">Twitter</a> | <a href="https://www.youtube.com"
          target="_blank">YouTube</a></p>
    </div>
    {% else %}
    <div class="row headline">
      <h2>ピックアップされた12のWebページを検索します</h2>
      <p><a href="https://ja.wikipedia.org/wiki" target="_blank">Wikipedia</a> | <a href="https://kotobank.jp"
          target="_blank">コトバンク</a> | <a href="https://dictionary.goo.ne.jp" target="_blank">goo 辞書</a> | <a
          href="https://matome.naver.jp" target="_blank">Naverまとめ</a></p>
      <p><a href="https://chiebukuro.yahoo.co.jp" target="_blank">Yahoo! 知恵袋</a> | <a href="https://oshiete.goo.ne.jp"
          target="_blank">教えて! goo</a> | <a href="https://qiita.com" target="_blank">Qiita</a></p>
      <p><a href="https://teratail.com" target="_blank">teratail</a> | <a href="https://ja.stackoverflow.com"
          target="_blank">Stack Overflow</a> | <a href="https://news.google.com/?hl=ja&gl=JP&ceid=JP:ja"
          target="_blank">Google ニュース</a></p>
      <p><a href="https://twitter.com" target="_blank">Twitter</a> | <a href="https://www.youtube.com"
          target="_blank">YouTube</a></p>
    </div>
    {% endif %}

    {% if not current_user.is_authenticated %}
    <div class="row">
      <hr class="hl">
    </div>

    <div class="row headline">
      <h2>新規登録(ログイン)すると自分好みに検索するWebページを設定できるようになります</h2>
      <div class="guide_div">
        <a class="guiding" href="{{ url_for('bp_auth.create_user') }}">新規登録はこちらから</a>
        <a class="guiding" href="{{ url_for('bp_auth.login') }}">ログイン</a>
      </div>
    </div>
    {% endif %}

    <div class="row">
      <hr class="hl">
    </div>

    <div class="row headline">
      <h2>調べたいWebサイトを厳選、比較し効率的な検索を可能にします</h2>
    </div>

    <div class="row">
      <hr class="hl">
    </div>

    <div class="footer">
      <p>お問い合わせ(準備中)</p>
    </div>

    <div class="footer footer-low">
      <p>&copy; Misprochef</p>
    </div>

  </div>
  <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
    integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
    crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
    integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1"
    crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
    integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
    crossorigin="anonymous"></script>

</body>

</html>

myapp/templates/layout.html
<!DOCTYPE html>
<html lang="ja">

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>{{ title }}</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
        integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.11.2/css/all.css">
    <link rel="icon" href="../static/img/left_32.ico">
    <link rel="apple-touch-icon" sizes="151x151" href="../static/img/left_151.png">
    <link rel="stylesheet" href="../static/styles_layout.css">
</head>

<body>
    <div class="container">
        <div class="items">

            <header>
                <div class="row">
                    <div class="col-md-12 title">
                        <a href="/">
                            <i class="fas fa-align-left d-inline-block"></i>
                            <p>HOME</p>
                        </a>
                    </div>
                </div>
            </header>

            <h2>{{ title }}</h2>


            {% with messages = get_flashed_messages(with_categories=true) %}
            {% if messages %}
            {% for category, message in messages %}
            <div class="alert alert-{{ category }}">
                {{ message }}
            </div>
            {% endfor %}
            {% endif %}
            {% endwith %}

            {% block content %}
            {% endblock %}

        </div>

        <div class="row">
            <hr class="hl-footer">
        </div>

        <div class="footer">
            <p>お問い合わせ (準備中)</p>
        </div>

        <div class="footer footer-low">
            <p>&copy; Misprochef</p>
        </div>

    </div>
</body>

</html>

myapp/templates/removed.html
<!-- wikipediaのハートレールver -->
<div class="col-md-4">
  <div class="card" style="width: 15rem;">
    <a href="https://ja.wikipedia.org/wiki/{{keyword}}">
      <img src="https://capture.heartrails.com/400x504?https://ja.wikipedia.org/wiki/{{keyword}}" alt="">
      <div class="card-body">
        <p class="card-text">
          Wikipedia
        </p>
      </div>
    </a>
  </div>
</div>

<!-- デフォルトver -->
<div class="col-md-4">
  <div class="card" style="width: 18rem;">
    <a href="/">
      <svg class="bd-placeholder-img card-img-top" width="100%" height="200" xmlns="http://www.w3.org/2000/svg" preserveAspectRatio="xMidYMid slice" focusable="false" role="img" aria-label="Placeholder: Image cap"><title>Placeholder</title><rect width="100%" height="100%" fill="#868e96"/><text x="50%" y="50%" fill="#dee2e6" dy=".3em">Image cap</text></svg>
      <div class="card-body">
        <p class="card-text">
          {{keyword}}
        </p>
      </div>
    </a>
  </div>
</div>

<!-- YouTubeのハートレール -->
<div class="col-md-4">
  <a href="https://www.youtube.com/results?search_query={{keyword}} " target="_blank">
    <div class="card-header bg-white border-white text-secondary">
      <i class="fab fa-youtube" style="color: #F00"></i>
      YouTube
    </div>
    <img src="https://capture.heartrails.com/400x450?https://www.youtube.com/results?search_query={{keyword}}" alt="YouTubeの検索結果へGo">
  </a>
</div>